<a href="https://colab.research.google.com/github/Udaykiran06-art/DS---ML---K-FOLD-CROSS-VALIDATION/blob/main/ML_K_FOLD_VALIDATION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Dataset is loading

from sklearn.datasets import load_digits

digits = load_digits()

print("Dataset is loading")


Dataset is loading


In [ ]:
#Splitting the data into train and test datasets

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

digits = load_digits()

X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.2)

print("splitting the data into train and test")

splitting the data into train and test


In [ ]:
#Applying logistic regression

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

digits = load_digits()

X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target, test_size=0.3)

lr = LogisticRegression()
lr.fit(X_train,y_train)
print(lr.score(X_test,y_test))

0.9537037037037037


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
#Applying SVM algorithm

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target, test_size=0.3)

svm = SVC()
svm.fit(X_train,y_train)

print(svm.score(X_test,y_test))

0.9907407407407407


In [ ]:
#Applying Random forest algorithm

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

digits = load_digits()

X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

rf = RandomForestClassifier()
rf.fit(X_train,y_train)

print(rf.score(X_test,y_test))

0.9740740740740741


In [ ]:
#K fold cross validation

from sklearn.model_selection import KFold

kf = KFold(n_splits=3)

print(kf)

KFold(n_splits=3, random_state=None, shuffle=False)


In [ ]:
#K fold cross validation: Example

from sklearn.model_selection import KFold

kf = KFold(n_splits=3)

for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
        print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [ ]:
#Logistic regression model performance using cross_val_score

from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression

digits = load_digits()

a = LogisticRegression(solver = 'lbfgs',max_iter = 5000)
scores = cross_val_score(a,digits.data,digits.target,cv=3)

print(scores)

[0.91986644 0.94156928 0.91652755]


In [ ]:
#SVM model performance using cross_val_score

from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_digits
from sklearn.svm import SVC

digits = load_digits()

b = SVC()
scores = cross_val_score(b,digits.data,digits.target,cv=3)

print(scores)

[0.96494157 0.97996661 0.96494157]


In [ ]:
#Random Forest model performance using cross_val_score

from sklearn.model_selection import cross_val_predict
from sklearn.datasets import load_digits
from sklearn.ensemble import RandomForestClassifier

digits = load_digits()

c = RandomForestClassifier()

scores = cross_val_score(c,digits.data,digits.target,cv=3)

print(scores)

[0.93989983 0.95659432 0.92487479]


In [ ]:
#Checking average of all model scores

from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

digits = load_digits()

a = LogisticRegression(solver= 'lbfgs',max_iter=5000)
b = SVC()
c = RandomForestClassifier()

scores1 = cross_val_score(a, digits.data, digits.target, cv=3)
scores2 = cross_val_score(b, digits.data, digits.target, cv=3)
scores3 = cross_val_score(c, digits.data, digits.target, cv=3)

print(np.average(scores1))
print(np.average(scores2))
print(np.average(scores3))

0.9259877573734001
0.9699499165275459
0.9360044518642181
